networks:
  scylla-net:
    driver: bridge

services:

  scylla-1:
    image: "scylladb/scylla:6.1"  # cassandra:4.1.3
    container_name: scylla-1
    command:
      - --reactor-backend=epoll
    networks:
      - scylla-net
    volumes:
      - scylla-node-1:/var/lib/scylla:rw
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 10s
      timeout: 10s
      retries: 60
    cpus: 3
    mem_limit: 8gb

  scylla-2:
    image: "scylladb/scylla:6.1"  # cassandra:4.1.3
    container_name: scylla-2
    command:
      - --seeds=scylla-1
      - --reactor-backend=epoll
    networks:
      - scylla-net
    volumes:
      - scylla-node-2:/var/lib/scylla:rw
    depends_on:
      scylla-1:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 10s
      timeout: 10s
      retries: 60
    cpus: 3
    mem_limit: 8gb

  scylla-3:
    image: "scylladb/scylla:6.1"  # cassandra:4.1.3
    container_name: scylla-3
    command:
      - --seeds=scylla-1
      - --reactor-backend=epoll
    networks:
      - scylla-net
    volumes:
      - scylla-node-3:/var/lib/scylla:rw
    depends_on:
      scylla-2:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 10s
      timeout: 10s
      retries: 60
    cpus: 3
    mem_limit: 8gb

volumes:
  scylla-node-1:
  scylla-node-2:
  scylla-node-3:
